### ISSUE TITLE
Compilation-time conditionalizing

### ISSUE THREAD

**Issue by phoe** [atgreen/trivial-system-loader#1]
https://github.com/atgreen/trivial-system-loader/blob/25348dac21e224b7ac81f75bb90f0cf1de71b711/trivial-system-loader.lisp#L41-L45

If `trivial-system-loader` is compiled before `ocicl`, then `ocicl` will not be used even after `ocicl` is loaded later; more, a version compiled with `ocicl` can then error on load when `trivial-system-loader` FASLs are loaded before `ocicl` is loaded, leading to a package-not-found error.

This should instead use execution-time `when` over `find-package` and then `funcall` over `find-symbol` to avoid such cases.

**Comment by atgreen** [comment]
Thanks for the feedback.  Would a similar problem exist if
trivial-system-loader is compiled before quicklisp?

**Comment by phoe** [comment]
Yes. (To be precise - if it is compiled before Quicklisp is loaded.)

**Comment by atgreen** [comment]
The idea behind both quicklisp and ocicl is that you load their runtimes in your .sbclrc, so this wouldn't be a problem in most cases.  However.. if we can do better...

I actually took your approach on my first attempt, but then got stuck on this part:

            (let ((ocicl-runtime:*download* t)
                    (ocicl-runtime:*verbose* (or verbose (not silent))))
                (asdf:load-system system))
How do you do the dynamic binding when ocicl-runtime may not be loaded?

**Comment by phoe** [comment]
You find the symbol via `find-package` and pass it to `progv` which does not require symbols to be resolved at compilation time. The following should work, but I haven't tested it:

```lisp
(defun load-system (systems &key (verbose nil) (silent t))
  "Load system SYSTEMS, potentially downloading them from an external
 repository.  SYSTEMS may be a single system or a list of
 systems. Loader behavior is modified by VERBOSE and SILENT."
  (unless (listp systems)
    (setf systems (list systems)))
  (flet ((try-load-system (system)
           (or
            (when (find-package '#:ocicl)
              (progv (list (find-symbol '#:*download* '#:ocicl)
                           (find-symbol '#:*verbose* '#:ocicl))
                  (list t (or verbose (not silent)))
                (funcall (find-symbol '#:load-system '#:asdf) system)))
            (when (find-package '#:quicklisp)
              (funcall (find-symbol '#:quickload '#:quicklisp)
                       system :verbose verbose :silent silent))
            (when (find-package '#:asdf)
              (funcall (find-symbol '#:load-system '#:asdf) system))
            (error "Unable to find any system-loading mechanism."))))
    (mapcar #'try-load-system systems)))
```

**Comment by atgreen** [comment]
progv?  Common Lisp is a seemingly never-ending journey of learning!
Your code required a few changes out of the box, but was very close.  I would like to credit you in the README, since now this code is almost all yours :)  Do you have any objections to this?

**Comment by phoe** [comment]
Yep, `progv` is one of the absolutely handy arcane tools that you always wish you had until you realize that it's actually always been there the whole time. (For maximum mind-blow-ness, wait until you realize that it's the only standard way to make a dynamic variable unbound in some dynamic scope without unbinding it globally.)

And, sure, feel free to do so.
